/**
 * Creates a new RsaOaepParams object.<br />
 * @see {@link http://www.w3.org/TR/WebCryptoAPI/#dfn-RsaOaepParams}
 * 
 * @private
 * @constructs RsaOaepParams
 * @extends Algorithm
 * @returns {RsaOaepParams} Newly created RsaOaepParams object
 */
function RsaOaepParams() {
  
  /**
   * The optional label/application data to associate with the message.
   * 
   * @type {BufferSource}
   */
  this.label;
}
extend(Algorithm, RsaOaepParams);

/**
 * Initializes this RsaOaepParams with the values given as paramter.
 * 
 * @private
 * @param {object} alg The values which should be used to intitialize
 * the RsaOaepParams.
 * @returns {RsaOaepParams} The initialized RsaOaepParams
 */
RsaOaepParams.prototype.init = function(alg) {
  // Call parent init function
  RsaOaepParams._super.init.call(this, alg);
  
  if(alg.label) {
    if(!isBufferSource(alg.label)) {
      throw new TypeError('RsaOapParams: label: Not a BufferSource');
    }
    this.label = alg.label;
  }
  return this;
};


/**
 * Returns the encrypted data corresponding to the data, algorithm and key 
 * given as parameters.<br />
 * Can only be used with RSA-OAEP algorithm.<br />
 * @see {@link http://www.w3.org/TR/WebCryptoAPI/#rsa-oaep-operations}
 * 
 * @private
 * @param {Object} normAlgo The encryption function to use.
 * @param {CryptoKey} key The key to be used for the encryption.
 * @param {ArrayBuffer | ArrayBufferView} plaintext The data to be encrypted.
 * @returns {Promise} A Promise that returns the ciphertext generated by 
 * the encryption of the data as an ArrayBuffer.
 */
function encrypt_RSA_OAEP(normAlgo, key, plaintext) {
  
  if(key.type !== 'public') {
    throw new InvalidAccessError(
            'key.usages does not permit this operation');
  }

  var label;
  if(normAlgo.label === undefined) {
    label = new ArrayBuffer(0);
  } else {
    label = getBuffer(normAlgo.label);
  }
      
  var encFn;
  switch(key.algorithm.hash.name) {
    case "SHA-256":
      encFn = asmCrypto.RSA_OAEP_SHA256.encrypt;
      break;
    default:
      throw new NotSupportedError('Not supported yet: hash: ' 
              + key.algorithm.hash.name);
  }
  try {
    var ciphertext = encFn(getBuffer(plaintext), key._handle, label);
  } catch(err) {
    throw new OperationError(err);
  }
  
  // TODO: Fix buffer length problem
  // Plaintext is alread Uint8Array but its internal buffer has
  // wrong byteLength. Solve this by create a new ArrayBuffer.
  return new Uint8Array(ciphertext).buffer;
}

/**
 * Returns the cleartext corresponding to the ciphertext, algorithm and key 
 * given as parameters.<br />
 * Can only be used with RSA-OAEP algorithm.<br />
 * @see {@link http://www.w3.org/TR/WebCryptoAPI/#rsa-oaep-operations}
 * 
 * @private
 * @param {Object} normAlgo The encryption function to use.
 * @param {CryptoKey} key The key to be used for the decryption.
 * @param {ArrayBuffer | ArrayBufferView} ciphertext The data to be decrypted.
 * @returns {Promise} The cleartext corresponding to the ciphertext, algorithm
 * and key given as parameters.
 */
function decrypt_RSA_OAEP(normAlgo, key, ciphertext) {
  
  if(key.type !== 'private') {
    throw new InvalidAccessError(
            'key.usages does not permit this operation');
  }
  var label;
  if(normAlgo.label === undefined) {
    label = new ArrayBuffer(0);
  } else {
    label = getBuffer(normAlgo.label);
  }
  
  var decFn;
  switch(key.algorithm.hash.name) {
    case "SHA-256":
      decFn = asmCrypto.RSA_OAEP_SHA256.decrypt;
      break;
    default:
      throw new NotSupportedError('Not supported yet: hash: ' 
              + key.algorithm.hash.name);
  }
  try {
    var plaintext = decFn(getBuffer(ciphertext), key._handle, label);
  } catch(err) {
    throw new OperationError(err);
  }
  
  // TODO: Fix buffer length problem
  // Plaintext is alread Uint8Array but its internal buffer has
  // wrong byteLength. Solve this by create a new ArrayBuffer.
  return new Uint8Array(plaintext).buffer;
}